### ISSUE TITLE
最后一个　确定　不能点啊

### ISSUE THREAD

**Issue by heng5011** [sunowsir/rj-aux.sunowsir.com.github#1]
![深度截图_选择区域_20191212182926](https://user-images.githubusercontent.com/47092895/70704646-671dad80-1d0d-11ea-8470-76c2c1d5a2e3.png)

登录成功之后，不能点确定，　因为点过之后会　重启网卡　然后回到最初没连网的地方　上不了网

**Comment by sunowsir** [comment]
反馈收到，由于没有真实环境测试，因此不能保证一定修复，但是将会在下一个版本尝试修复，请关注版本发布，谢谢！

**Comment by sunowsir** [comment]
为了解决该问题，新版本已发布，请下载体验，如果已经可以稳定使用请反馈一下，谢谢。
